import PageTransition from "@/components/PageTransition";
import "./globals.css";

// components
import Header from "@/components/Header";
import StairTransition from "@/components/StairTransition";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-grotesk antialiased items-center">
        <Header />
        <StairTransition />
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}
